# Generated by Django 4.0.3 on 2022-03-29 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pacient',
            name='diagnoses',
        ),
        migrations.AddField(
            model_name='pacient',
            name='diagnoses',
            field=models.ManyToManyField(to='mainapp.diagnoses'),
        ),
    ]
