# Generated by Django 4.0.3 on 2022-03-29 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_remove_pacient_diagnoses_pacient_diagnoses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacient',
            name='diagnoses',
            field=models.ManyToManyField(related_name='diagnos', to='mainapp.diagnoses'),
        ),
    ]
